### PR TITLE
First thing I tried to do

### PR DESCRIPTION
**Pull request by MylesBorins**
I wanted to do so much more

### CODE REVIEW

**Comment by jkup** [comment]
hahahha <3

**Comment by MylesBorins** [comment]
I only get one right

**Comment by jkup** [comment]
No I think as many as you want just never two back to back

**Comment by jkup** [comment]
I'm sort of making this up as I go along though lol

**Comment by MylesBorins** [comment]
Also, do npm scripts count as config?

**Comment by jkup** [comment]
Yeah I think you would be fine to add as much npm / babel / eslint stuff as you need with each commit.. same goes for requires

**Comment by MylesBorins** [comment]
LOL... I got off and write 200 lines of modules and config and make it one line in this project

**Pull request merged**
